### ISSUE TITLE
Providerの導入

### ISSUE THREAD

**Issue by OsgMoyasy** [OsgMoyasy/mvvm_template#1]
## 概要
MVVMのアーキテクチャで実装するにあたり必要なProviderパッケージを導入する

## 作業一覧
- [ ] providerパッケージの導入を行う

### providerパッケージの導入
- [こちらのページ](https://pub.dev/packages/provider)からproviderパッケージの最新版を確認
  - installingタブを確認するとわかりやすいかも
- pubspec.yamlにパッケージ名とバージョンを記述(yamlファイルなのでスペースの数に注意)
```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # 追記
  provider: ^4.3.2+2
```
- Pub getを行う
  - AndroidStudioならpubspec.yamlを開いているときに右上に表示されているはず

上記の作業でProviderの導入は完了
